---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Create Services
    type: deployer
    target:
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      cf create-service cloudantNoSQLDB Lite Twitter-Chatter-db
      cf create-service tone_analyzer lite Twitter-Chatter-ta
  - name: Deploy
    type: deployer
    target:
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      # generate a random 4 digit number to append to app name to use as the 
      # host name.  This will be more likely to be unique in the mybluemix.net
      # space
      cf push "${CF_APP}" -n "${CF_APP}-$(( ( RANDOM % 9999 ) + 1000 ))"
